### ISSUE TITLE
svtplay-dl and Widevine?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1189]
Is it possible for svtplay-dl to use Widevine or maybe something else like the [inputstreamhelper](https://github.com/emilsvennesson/script.module.inputstreamhelper)

**Comment by SYSophie** [comment]
@Sopor possible to use in what sense? This is used for diagnostics of DRM-playback and checks modules.

If you intend to break DRM I need to stress that this isn't legal and it isn't likely that svtplay-dl, youtube-dl or similar tools will support breaking this because of this.

L3 is theoretically possible to break. Which is the lower level of Widevine however it's limited to lower resolutions. If you'e more interested please read this article [Link](https://fidusinfosec.com/breaking-content-protection-on-streaming-websites/)

**Comment by Sopor** [comment]
Kodi can use Widevine to playback, so why can't svtplay-dl use it to download DRM protected files?

**Comment by SYSophie** [comment]
@Sopor Kodi is using the same proprietary Widevine CDM (Content Decryption Module) as any other player used by i.e Netflix, Disney+. 

The module insures that files isn't saved locally and that it isn't possible to save or make copies, which tools such as svtplay-dl wants to do.

What kodi is doing is far from illegal.

Decrypting the content outside the CDM, breaking the DRM and saving it locally however is illegal and would go against Github's policies. There are examples on other repos that has published tools that has ripped widevine content that have been completely removed.

Again I think it's good if you read the article I linked you - [Link](https://fidusinfosec.com/breaking-content-protection-on-streaming-websites/)
