### ISSUE TITLE
Sound for 3-5 seconds then nothing

### ISSUE THREAD

**Issue by Macatho** [spaam/svtplay-dl#1217]
Tried downloading from both SVTPLAY and TV4-PLAY. Both resulting in sound cutting out after 3-5 seconds.

Any suggestions? Thanks.
Super cool app btw :)

**Comment by SweDennis** [comment]
Hi, this is somewhat of a funny fault report, to me, but I don't mean this the wrong way, at all. The reason for me saying this is that I've sometimes had the opposite "problem", that the first 10-15 seconds were silent before the sound. 
I've not bothered myself with understanding the reason, because I can't see any possible way that this could be either caused, nor fixed, by svtplay-dl, this must surely be an issue with either the stream itself or ffmpeg, at least to my understanding, but lets see what response is given. :)

/Dennis

**Comment by SweDennis** [comment]
What version of ffmpeg are you using btw? Not being an expert myself, but that would perhaps be relevant.

/Dennis

**Comment by spaam** [comment]
what ffmpeg version do you have?  do you use HLS or DASH when downloading?  example url?

**Comment by Macatho** [comment]
ffmpeg -version
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers

Btw HLS/Dash made no difference. tried -p HLS

Updating ffmpeg now...
Jesus this was annoying to find it as it was so hidden. I had huge problems finding it in my PATH to remove the old version. Apparently Imagemagick thought it was a super good idea to have ffmpeg in its main folder. And I also thought I could just move the new ffmpeg folder to top of the PATH list - nope.

**Anywho, updated to the newest FFMPEG and it works flawlessly now. Thanks for that support.**

Also, this was a bit interesting because the audio kind of cut off just as there was a scene change. Maybe something with SVT rapports stream? I'm not sure.

**Comment by SweDennis** [comment]
Don't want to hi-jack anything, but since I've had similar issues I can honestly say that on the rare occasions that I've had issues, with Anything related to such things, being it sound dropping, or being out of sync, it's always been related to HLS. As I type this, the above response to the OP came in, and yes, ffmpeg is a good thing to have updated. I use a static Linux build, updated every fortnight or so, and since I started doing that, I have had very few problems. There's only so much svtplay-dl can help in these cases. :)

**Comment by spaam** [comment]
i have thinking about adding a warning or so if someone using a old version of ffmpeg. this is not the first time i got a ticket about this issue 🤔

**Comment by SweDennis** [comment]
For every new release, set a semi-hard error on a suitable version of ffmpeg, and scream about it if not met. Even if it still works, you will have stated your case, and I think most people using your software are able to handle things, as long as pointed in the right directions.

Oavsett, fantastiskt bra jobb, jobba på, och jag hoppas du får den uppskattning du förtjänar. :-D

/Dennis

**Comment by Sopor** [comment]
@Macatho If this is solved you maybe should close it?

**Comment by Macatho** [comment]
Solved
