### ISSUE TITLE
Support for kunskapskanalen.se

### ISSUE THREAD

**Issue by dotdeas** [spaam/svtplay-dl#1226]
Support for https://kunskapskanalen.se that is run by SVT and SR.

**Comment by Sopor** [comment]
That is totally useless because all those programs on kunskapskanalen.se you will find on svtplay.se.

https://kunskapskanalen.se/program/36273/djurvarldens-underbara-ungar-sasong-1-avsnitt-2

https://www.svtplay.se/djurvarldens-underbara-ungar

Even the link on kunskapskanalen.se points to svtplay.se.

**Comment by dotdeas** [comment]
True that, after looking into it some more it was actually linked to ur.se so all good. My mistake!
