### ISSUE TITLE
viafree.se stopped working sometime after 15 August

### ISSUE THREAD

**Issue by towil1** [spaam/svtplay-dl#1243]
### svtplay-dl versions:

svtplay-dl 2.4-51-g6bde2e7

### Operating system and Python version:

Ubuntu 18.04.5 LTS
Python 2.7.17
Python 3.6.9

### What is the issue:

Looks like something changed at viafree.se since 15 August when it was working fine, but with an URL that worked then

svtplay-dl --verbose https://www.viafree.se/program/drama/philomena/1040471

it now gives

DEBUG [1598001634.080176] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4-51-g6bde2e7
DEBUG [1598001634.083071] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: viaplay
DEBUG [1598001634.083142] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/drama/philomena/1040471'
DEBUG [1598001634.0849042] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se
DEBUG [1598001634.5920017] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/philomena/1040471 HTTP/1.1" 302 77
DEBUG [1598001634.7837136] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/philomena/film/1040471 HTTP/1.1" 200 None
DEBUG [1598001634.7969584] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://viafree.mtg-api.com/identity/viafree/auth/pwd/sessions'
DEBUG [1598001634.798112] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): viafree.mtg-api.com
DEBUG [1598001635.201763] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://viafree.mtg-api.com:443 "POST /identity/viafree/auth/pwd/sessions HTTP/1.1" 200 None
DEBUG [1598001635.2039986] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://playapi.viafree.tv/v3/videos/stream-links/1040471?device=web'
DEBUG [1598001635.2051349] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playapi.viafree.tv
DEBUG [1598001635.4885674] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playapi.viafree.tv:443 "GET /v3/videos/stream-links/1040471?device=web HTTP/1.1" 200 168
DEBUG [1598001635.4893186] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting None
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 66, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/viaplay.py", line 71, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 39, in request
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 506, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 449, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by towil1** [comment]
It is working now, must have been a temporary issue

**Comment by krokerik** [comment]
I subscribed to this issue because I had the same issue and it hasn't been resolved for me. I get the following error message:

`svtplay-dl --verbose https://www.viafree.se/program/drama/philomena/1040471
DEBUG [1598395421.6673243] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+51.g6bde2e7-py3.6.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.4+51.g6bde2e7
DEBUG [1598395421.675804] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+51.g6bde2e7-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: viaplay
DEBUG [1598395421.6768541] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+51.g6bde2e7-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/drama/philomena/1040471'
DEBUG [1598395421.681046] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se
DEBUG [1598395421.8608837] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/philomena/1040471 HTTP/1.1" 302 None
DEBUG [1598395421.919737] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/philomena/film/1040471 HTTP/1.1" 200 None
DEBUG [1598395421.9292493] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+51.g6bde2e7-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/drama/philomena/sasong-1'
DEBUG [1598395421.9473925] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/philomena/sasong-1 HTTP/1.1" 200 None`

**Comment by towil1** [comment]
Strange, that Philomena URL worked just fine for me just now:

`svtplay-dl  https://www.viafree.se/program/drama/philomena/1040471
INFO: Selected to download hls, bitrate: 5186 format: h264
INFO: Outfile: philomena-1040471-viaplay.audio.ts
[042/704][====............................................................................] ETA: 0:00:33^C`
