### ISSUE TITLE
File naming changed for Svtplay?

### ISSUE THREAD

**Issue by Swedie** [spaam/svtplay-dl#1342]
### What is the issue:
It has now dropped season and episode number in the naming.
Before it was: exit.s02e01.1-alla-har-nat-pa-nan-f9ae953-svtplay
And now it's: exit.1..alla.har.nat.pa.nan-2e1d1a2-svtplay

Running the following command: svtplay-dl -S https://www.svtplay.se/video/30346202/exit/exit-2-sasong-2-alla-har-nat-pa-nan

**Comment by krokofant** [comment]
I just updated and can replicate your issue, and I also noticed that the generated id for the older episodes (f9ae953 and 2e1d1a2 in your example) differs.

So using something like this no longer works to download the missing episodes, it'll re-download the ones you have since the checksum(?) is different:
```
svtplay-dl.exe --subtitle --all-episodes https://www.svtplay.se/exit
```
This will start downloading s01e01 into:
`exit.s01e01.avsnitt.1-18508e5-svtplay.mp4`
While this file has already been downloaded:
`exit.s01e01.avsnitt.1-18508e5-svtplay.mp4`

**Comment by spaam** [comment]
i made some changes to fix this. it will be in 3.3 tonight.

**Comment by krokofant** [comment]
@spaam Do you think this is part of the issue with differing episode ids I'm experiencing as well or should I create another issue?

**Comment by spaam** [comment]
im not sure. i guess they changed the id numbers of the video from before and now. maybe we need to use something else for id? 🤔

**Comment by krokofant** [comment]
@spaam I create another issue to track the duplicates / id change scenario #1343 

I've tested your latest snapshot (20210314_180119) and it seems there is one dot too many in the file name:
`svtplay-dl --subtitle https://www.svtplay.se/video/30435884/exit/exit-2-sasong-2-tro-pa-sig-sjalv`
gives
`exit.s02e03.3..tro.pa.sig.sjalv-ed86ee2-svtplay.mp4`
