### ISSUE TITLE
Öppet arkiv - no season or episode numbers

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#140]
When i download from Öppet arkiv i don't get any season or episode numbers:
arkiv-rederiet-farlig-kryssning-1058509-svtplay.ts
I can see text on every episode: "Avsnitt 1 av 318: Farlig kryssning" and the URL have it too http://www.oppetarkiv.se/video/1058509/rederiet-sasong-1-avsnitt-1-av-318
I have tried with -A and without, no difference :cry:

**Comment by Sopor-** [comment]
I was downloading
http://www.oppetarkiv.se/etikett/titel/N_P_M%C3%B6ller_fastighetssk%C3%B6tare/
but as you can see the first episode have no number so that episode will only be called
n.p.moller.fastighetsskotare.vinstlotten-2547052-svtplay.ts
and if there have been more episodes like this you will not know the episode number. If you have added my suggestion, start with 01, 02, 03 and so on, the numbers should have been correct because it will be download in the same order svt have added them to öppet arkiv :)
Even if the season number should be missing, the number on the download order should be in the correct view order.

**Comment by Sopor-** [comment]
Another one that will be totally messed up
http://www.oppetarkiv.se/etikett/titel/Sk%C3%A5nska_mord/

**Comment by spaam** [comment]
http://www.oppetarkiv.se/etikett/titel/På%20spåret/ is a mess deluxe.. maybe we should remove episode numbers for öppet arkiv?

**Comment by Sopor-** [comment]
That's why i suggest an alternative way to download from Öppet arkiv. At least SVT will use date order and if you start at 01 for the first download, 02 on the next and so on you will get them in the correct order.
Btw, episode number seems to work very well even if i sometimes get double episode numbers 'flykten.s01e01.del.1.av.4-1999583-svtplay.ts'
