### ISSUE TITLE
Viaplay Poland inquiry

### ISSUE THREAD

**Issue by darnow64** [spaam/svtplay-dl#1452]
Hello, how can I download content from viaplay.pl

I am asking because there is, unfortunately, no website https://viafree.pl/

Thanks for the answer.

**Comment by spaam** [comment]
i dont understand polish but the website looks pretty similar to the swedish one viaplay.se. i  guess polish one have movies and tv series too and its a paid website.  sadly because of those things it will have [DRM ](https://en.wikipedia.org/wiki/Digital_rights_management). we cant download and decrypt those files because of it.
