### ISSUE TITLE
Can't get the program to even start

### ISSUE THREAD

**Issue by CurryBurken** [spaam/svtplay-dl#1547]
### svtplay-dl versions: latest 4.24 x64 windows.

Run `svtplay-dl --version`

**Comment by spaam** [comment]
expected behavior. its not really a window application, its a console application.  you need to open powershell , then go to the directory where you downloaded svtplay-dl. like ` cd .\Downloads\svtplay-dl-amd64`  if you put it in your downloads folder.  when you have done  that you need to type `.\svtplay-dl.exe Arguments`  replace `Arguments` with the url you want to download or so. you can read https://svtplay-dl.se/usage/ on how to use the application.  i do recommend downloading https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip and put the ffmpeg.exe in the same directory as `svtplay-dl.exe` .  you need this tool so svtplay-dl.exe can automagically merge audio and video files to one file so you dont have to to it manually :)

**Comment by spaam** [comment]
i guess this is fixed? 🤔
