### ISSUE TITLE
SVTplay now has two "different" subtitle tracks

### ISSUE THREAD

**Issue by tinsun** [spaam/svtplay-dl#1587]
Greetings!
I've just noticed that Swedish language programs now has two different subtitles, "Svenska" and "Svenska (allt tal)". It seems to default to Svenska, meaning you won't get the full subtitles. Trying --all-subtitles does't seem to make any difference; only "Svenska" seems to be downloaded. Any ideas?

Thank you in advance!

**Comment by spaam** [comment]
it seems like you didnt read the issue template and sharing the version of svtplay-dl you are using and what url you tried to download the video and subs. because of that im assuming you are using an old version of svtplay-dl. try upgrading to the latest 4.69. it should be fixed in 4.26 that was released beginning of 2023-10.
 if its still an issue, feel free to  share what version you are using and the url you having issues with :)
