### ISSUE TITLE
svtplay-dl does not support repoducible builds

### ISSUE THREAD

**Issue by olof** [spaam/svtplay-dl#210]
A group of debian contributors are working on reproducing builds, i.e. verify that a given binary was generated by the specified source. Building svtplay-dl twice from the same source generates binaries with some variations (which leads to md5 mismatch), so this is currently not possible for svtplay-dl. I haven't looked into what this variation is caused by, but it might be interesting to investigate and fix.

https://lists.debian.org/debian-devel-announce/2015/02/msg00007.html
https://reproducible.debian.net/rb-pkg/svtplay-dl.html

**Comment by spaam** [comment]
http://superuser.com/questions/403802/why-do-two-identical-zips-on-linux-have-different-md5-sum-values can be one reason. because i get different md5sums when i try it on my macbook and on my linux server with a clean tree.

if they complain about it, maybe we should use the setup.py install way instead.

**Comment by olof** [comment]
Fixed in 87ae56cacaed1d5e048e7c932ad8b7d964bb87e9.
