### ISSUE TITLE
Run instructions missing

### ISSUE THREAD

**Issue by kobbe** [spaam/svtplay-dl#357]
I just downloaded the program but there are no instructions on how to run the program! A small portion on the git read-me would be good. For example, the python module is named svtplay_dl, how would you know that? (I looked in the python installation folder)

Thanks!

**Comment by spaam** [comment]
What kind of information "From source " do i miss in the readme https://github.com/spaam/svtplay-dl#from-source?
i guess i could replace some of that info with "python setup.py install"   instead of make.  
during development process tell the user that they can: cd lib && python -m svtplay_dl <arugments here>

**Comment by kobbe** [comment]
I did not mean how to install the program but rather how to run it after I have installed it. Nowhere does it say "To run the application do: python -m svtplay_dl url". How would I know that the package is named svtplay_dl in python rather than svtplay-dl? That the command to download is not "python -m svtplay-dl"

**Comment by spaam** [comment]
ah okey! sure.. it should be  just svtplay-dl. i can fix that. thanks for the input btw :)
