### ISSUE TITLE
urplay.se --all-episodes finds nothing

### ISSUE THREAD

**Issue by albint** [spaam/svtplay-dl#374]
The --all-episodes switch does not work with urplay.se. No episodes are found, not even the linked one.

```
11:32:34 > svtplay-dl -A http://urplay.se/program/193713-vims-i-rymden-jupiter
INFO: Couldn't retrieve episode list as rss, trying to scrape
11:32:35 > 
```

**Comment by qnorsten** [comment]
It seems like Urplay changed the layout on the links 
It would work if the following line is changes in the scrape_episodes function in  **/lib/svtplay_dl/service/urplay.py b/lib/svtplay_dl/service/urplay.py**
from
**for relurl in re.findall(r'<a class="puff tv video"\s+title="[^"]*"\s+href="([^"]*)"',**
to 
**for relurl in re.findall(r'<a class="card program"\s+href="([^"]*)"',**

but that breaks the functionality on urskola.se which have not changed the layout
But a check or something can probably be fixed with a simple check of the url. 
But I am sure spaam will fix this eventually

**Comment by spaam** [comment]
qnorsten, you are right but they still use "puff tv video" on urskola.se , need to add one extra way to detect urplay :)
