### ISSUE TITLE
SVTPlay-DL Chrome Extensions - [Feature function]

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#628]
**Hi, I wonder if a Chrome Extension for SVTPlay-DL will be available in the future!**

1.) Open a URL in the Chrome Browser and Press Download with SVTPlay-DL

**[Options]**

+Possibility to add parameters
+Possibility to choose download location (default/ask for each downloads)

2.) This should be very nice feature I think, and will do SVTPlay-DL very easy to use for beginners!

**Comment by iwconfig** [comment]
You can't just implement python code (svtplay-dl) into a chrome extension. You need some kind of gateway.

I started working on a solution for this using a websocket server as the gateway for a userscript client. The userscript is installed using the _Tampermonkey_ extension. Feel free to use it however you want but be warned, i will more than likely abandon this and maybe later in the future start over with something better. It's buggy and since svtplay.se changed to a secure protocol (HTTPS that is) after i wrote it, your browser need to accept a certificate from the websocket server so the client get accepted by CORS which is kinda hackish and cumbersome. A certificate is available in the repository though.

If you're a novice user this might be too complicated but [here it is](https://github.com/iwconfig/svtplay-dl-server) if you want to dive in to it. Again, it's buggy and cumbersome and don't expect it to be updated any time soon, if at all.

**Comment by stdlogin** [comment]
CLOSED THE ISSUE...
