### ISSUE TITLE
ValueError while determining language of subtitle

### ISSUE THREAD

**Issue by augustjanse** [spaam/svtplay-dl#659]
Encountered while executing:

    ./svtplay-dl -M --convert-subtitle-colors -t -A https://www.svtplay.se/skam?tab=sasong4

Results in (excerpt):

```
INFO: Episode 2 of 10
INFO: Url: http://www.svtplay.se/video/13356584/skam/skam-sasong-4-avsnitt-2
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.srt
INFO: Selected to download dash, bitrate: 3285
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.m4a
[184/184][===========================================================] ETA: 0:00:00
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.mp4
[185/185][===========================================================] ETA: 0:00:00
INFO: Merge audio, video and subtitle into skam.s04e02.avsnitt.2-eb0a706-svtplay.mp4
INFO: Determining the language of the subtitle.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 466, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 194, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 223, in get_all_episodes
  File "./svtplay-dl/svtplay_dl/__init__.py", line 333, in get_one_media
  File "./svtplay-dl/svtplay_dl/postprocess/__init__.py", line 166, in merge
  File "./svtplay-dl/svtplay_dl/postprocess/__init__.py", line 84, in sublanguage
  File "./svtplay-dl/svtplay_dl/postprocess/__init__.py", line 42, in query
  File "/usr/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
```

Occurs for episodes 2, 4, 7 and 9. Since the error occurs while merging, .m4a, .mp4 and .srt files are left.  If executing the command again, the episode will (predictably) be skipped. Equivalent error for targeting the specific affected episodes.

The left-over files seem fine, so the obvious workaround is either not requesting a merge or merging them yourself afterwards. Haven't tried this, though.

svtplay-dl 1.9.4 on Linux.

**Comment by augustjanse** [comment]
Seems like an exact duplicate of #619, not sure why @Skankhunter42 closed that though.

**Comment by spaam** [comment]
we can have t his one open and i will take a look at it this week. thanks for reporting the issue :)

**Comment by Skankhunter42** [comment]
Hello.

I closed that ticket because I didn't see the problem anymore when I stopped using -m when downloading the episodes. That's why I closed the ticket.

But the problem is still there it seems.

**Comment by iwconfig** [comment]
its because the episodes subtitle is hardcoded so the .srt-file does not contain enough sentences for `random.sample()` which is set to pick out at least eight random samples. For example, episode 2 contains only six short describing lines for the hearing impaired. I don't have time to work on this right now but i guess `random.sample()` is better suited in some conditional statement. Maybe the length of the .srt-file and if it is HI, then make a set with all the lines. Maybe a set is better anyway, regardless of length.

**Comment by bohelax** [comment]
This problem is clearly seen if you use -S with -M, and only if the .srt file is very short.
I have seen this before and today I got this:
[svtplay-dl_Bug-170904.txt](https://github.com/spaam/svtplay-dl/files/1275167/svtplay-dl_Bug-170904.txt)
Sorry, I tried to find a shorter sample, but the ones I've seen before no longer exist on svt play.

**Comment by bohelax** [comment]
I really would like someone to address this bug - it's extremely annoying when it happens - and it can't be that hard to fix.
A fresh link is "Finland 100 år SVT Play"
(https://www.svtplay.se/video/13105239/finland-100-ar/finland-100-ar-avsnitt-1)
which is only 29 minutes and available to 5 jun 2018

**Comment by iwconfig** [comment]
you're right, a fix is coming
