### ISSUE TITLE
Downloading from Svtplay gives crap files

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#811]
Hi, it seems like several different programs (but not all) on Svtplay can no longer be downloaded if you're using Mac and Brew (like me). It only results in ts-files that have the correct size but are not viewable. 

Here are two examples that don't work:

https://www.svtplay.se/video/16936518/aktuellt/aktuellt-16-feb-21-00-1?start=auto&tab=2018

https://www.svtplay.se/video/16936330/morgonstudion/morgonstudion-16-feb-06-00?start=auto&tab=2018

If there already is a solution to this problem, is it possible that an upgrade can be made on Brew as well? :)  Thank you!

**Comment by granbom** [comment]
If you remux the .ts file to mp4 it will work. Download with --remux parameter added. (I think next release with always remux these type of files).
Since you already downloaded these files, you can remux them with ffmpeg, will only take a few seconds.
If you don't have ffmpeg installed, first install it with: `brew install ffmpeg`
Then you remux with ffmpeg to a mp4 container instead.
```
ffmpeg -i aktuellt.fre.16.feb.21.00-0f31bd5-svtplay.ts -c copy aktuellt.fre.16.feb.21.00-0f31bd5-svtplay.mp4
```
Hope this helps =)

**Comment by dalgr** [comment]
Fixed in: https://github.com/spaam/svtplay-dl/pull/801
Try version: 1.9.9
