### ISSUE TITLE
Question: supress 'Already exist' message

### ISSUE THREAD

**Issue by manderss99** [spaam/svtplay-dl#862]
is ther anyway to supress already exist error message?
I just want message when downloaded or an actual error occurred.
Running from cron and dont want unneccessary emails.

**Comment by dalgr** [comment]
Have you tried `-s` or `--silent`

**Comment by dalgr** [comment]
Ok, you can use `-f` or `--force`, but it will overwrite existing files

**Comment by manderss99** [comment]
I do not want to download the existing files again.
I'm using the -A option and --all-last=1 to download the latest episode. run periodically from cron.

Why not make the message a warning instead of error and supress it when using --silent or --silent-semi?

**Comment by manderss99** [comment]
thanks but does not seem to work for silent-semi, I think there should be a parethesis around the test:

> -                if not options.silent or options.silent_semi:
> +                if not (options.silent or options.silent_semi):

**Comment by spaam** [comment]
@manderss99 you are right :)

**Comment by dalgr** [comment]
The behavior you are seeing is the way i intended to implement this. That it shall be possible to see the warning 'Already exist' when using `--silent_semi` but not `--silent`.
@spaam What do you think, If the intended behavior is to skip 'Already exist' for both `--silent` and `--silent_semi` i suggest to write:
```
if not options.silent:
```
Because if the option `silent_semi` is set then `silent` get automatically set to true.
See: https://github.com/spaam/svtplay-dl/blob/62a59549e94104f85b9c5fad659d1e914760c2eb/lib/svtplay_dl/__init__.py#L197

**Comment by manderss99** [comment]
The behavior I'm looking for is to get a message when something is downloaded but not when the file already exists.
do I get the downloaded message if I use silent?
I was under the impression that I needed to use silent-semi for that.

**Comment by manderss99** [comment]
tested, with --silent it does not give a message when downloaded an episode.
The current behaviour with --silent-semi is exactly what I want:
A message when downloaded a new episode and no  error when file already exists.
