### ISSUE TITLE
Dplay: no subtitles  and merge audio into existing files  - 1.9.11 

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#866]
I don't get any subtitles with version 1.9.10-10-gb9d6d5b of svtplay-dl when downloading from Dplay.se and if an episode already exists it will download the audio and merge with the existing file
```
INFO: Episode 1 of 2
INFO: Url: https://www.dplay.se/videos/helt-perfekt/helt-perfekt-1
INFO: Selected to download hls, bitrate: 6557
INFO: Outfile: helt-perfekt.s01e01.avsnitt.1.dirty.talk-41141-dplay.audio.ts
[130/130][==============================================================================================================] ETA: 0:00:00
INFO: Outfile: helt-perfekt.s01e01.avsnitt.1.dirty.talk-41141-dplay.ts
WARNING: File (helt-perfekt.s01e01.avsnitt.1.dirty.talk-41141-dplay.ts) already exists. Use --force to overwrite
INFO: Merge audio and video into helt-perfekt.s01e01.avsnitt.1.dirty.talk-41141-dplay.ts
```

**Comment by spaam** [comment]
great just when i released 1.9.11 :) 
this will have to wait until i fixed 2.0. im not pushing 2.0 back more

**Comment by spaam** [comment]
audio part is only happen to `hls` files with separate audio/video track. thanks to i added `.audio` at the end of the filename, because of that change `output` and `findexpisode` fail to detect that we already have the episode.  it worked great for `dash` because they have a separate file extension `m4a`. that is not the case for `ts` files.

**Comment by MaistroX** [comment]
I have the same issue!

Ex:

>

**Comment by MaistroX** [comment]
Maby we could get a small fix for just that "the missing subtitles" so we can "stay alive" untill 2.0? =)

**Comment by qnorsten** [comment]
The subtitle error is caused by this commit https://github.com/spaam/svtplay-dl/commit/4b64e1bb9fe0003c4035cf3ce53d3491750752bf#diff-d270417624a29285ade534bbf701a599
as an example m3u8 from dplay https://pastebin.com/Qn3fuzvV  only have the subtitle in an AUTOSELECT group and https://github.com/spaam/svtplay-dl/blob/4b64e1bb9fe0003c4035cf3ce53d3491750752bf/lib/svtplay_dl/fetcher/hls.py#L70 tells svtplay-dl to not parse that tag to fix https://github.com/spaam/svtplay-dl/issues/853

`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="100wvtt.vtt",LANGUAGE="sv",NAME="sv",AUTOSELECT=YES,DEFAULT=NO,FORCED=NO,URI="exp=1521616937~acl=%2f*~data=hdntl~hmac=558478673c19cc78d44c0a8d13b5bb92edb9e7c1a34738d52e7001fc6e91737a/1112635959-prog_index.m3u8?hdntl=exp=1521616937~acl=/*~data=hdntl~hmac=558478673c19cc78d44c0a8d13b5bb92edb9e7c1a34738d52e7001fc6e91737a&version_hash=6c4e7ada"`

I am not sure about the best way to fix this but at least the cause have been identified

**Comment by qnorsten** [comment]
I did an attempt to solve the subtitle problem in https://github.com/spaam/svtplay-dl/commit/1017f7dbcd39831d86a66e83894bcef72df79ad7 
I made some quick tests with a few dplay videos and a few viaplay videos to make sure that I did not break the fix for https://github.com/spaam/svtplay-dl/issues/853 

I pushed my fix in a separate branch for now https://github.com/spaam/svtplay-dl/tree/dplay-subtitle-bug as I would appritichate if a few people could checkout that branch and try it out with a few more HLS-services to make sure that I did not break any other service by accident.

**Comment by MaistroX** [comment]
Is there an *.exe file that one can download and test?

**Comment by qnorsten** [comment]
Not currently and I no longer have access to a working windows python environment. 
Perhaps someone else can generate one for you, or I might generate one later this week. 

If you want to try it out right now you have to follow the instructions : https://github.com/spaam/svtplay-dl#from-source but checkout the dplay-subtitle-bug branch instead master

**Comment by MaistroX** [comment]
I would more then appreciate it @qnorsten ! :)

**Comment by qnorsten** [comment]
I tried setting up a new python enviroment on windows but got some problem getting pyinstaller to work. So will not be making an exe file unfortunately.

**Comment by Gurkan911** [comment]
I tried downloading https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-17 with https://github.com/spaam/svtplay-dl/tree/dplay-subtitle-bug but unfortunately I did not get any subtitles.

**Comment by qclass** [comment]
I can confirm that the fix works for https://www.dplay.se/videos/gold-rush/mammoth-gold for example.
Problem is that I only get Danish srt...
Tried --all-subtitles with no luck.
When you go to website they have a selector in the player with 4 different languages..
Don't know how to fix it..any ideas?

**Comment by Sopor-** [comment]
It would be nice if the subtitle could be fixed because now i have to use an older version of svtplay-dl to download the subtitles :(

**Comment by Ronald987** [comment]
Sopor, which version did you get working with swedish subtitles? I´ve tried the past 4 releases with no luck.

**Comment by Sopor-** [comment]
@Ronald987 If you mean subtitles from TV4/Sjuan it will not work at all no matter what version you use. I believe it was Dplay or Viafree that i need to use an older version (1.9.9) to get the subtitles.

**Comment by Ronald987** [comment]
@Sopor- Thanks, i tried 1.9.9 but only get danish srt´s. I´m guessing because its the first available sub in the menu. Browsed through the code but can´t really get my head around where the language selector is in the code. Anyway, I'm hoping for a 2.0 with this issue resolved. And yes, its Dplay im downloading from.
