### ISSUE TITLE
Download from viafree.se no longer works

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#893]
Is it just me or does download from  viafree.se no longer work?

I only get "No video found" no matter which URL I try.

**Comment by JohnnyJorgensen** [comment]
Sure :-)

I tested these three, and none of them worked, so I assumed it was a general problem:

https://www.viafree.se/program/drama/advokaten/sasong-1/avsnitt-10
https://www.viafree.se/program/humor/last-man-on-earth/sasong-4/avsnitt-3
https://www.viafree.se/program/humor/last-man-on-earth/sasong-4/avsnitt-4

**Comment by dalgr** [comment]
Ok, the problem is the same as #888
Which I added a fix for yesterday, I have tested it with all of you urls and all work :)
@spaam Might be time for a release

So fix for #888 is in the master branch(stable code) but not released yet.
So, if you want to use the fix now you need to compile the code you self, by following https://github.com/spaam/svtplay-dl#from-source

**Comment by Karamba91** [comment]
I've also experienced some problems with downloading from viafree.se. The links above works fine after I downloaded the new code, but the link 
https://www.viafree.se/sport/folj-med-f-1-magasinet-pa-langpromenad-i-monacos-depa 
is giving me the following error:
`AttributeError: 'ServiceError' object has no attribute 'output'`

I'm running svtplay-dl 1.9.11
